language: go

# Force-enable Go modules, it will be unnecessary on Go 1.13+
env:
  - GO111MODULE=on

go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - make setup-ci
  - make lint
  - make vet
  - make test
